name: Build & Push Docker Image

on:
  push:
    branches:
      - "master"  # Or "main" if that's your default branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout code
      - uses: actions/checkout@v4

      # Step 2: Set up Docker Buildx
      - uses: docker/setup-buildx-action@v3

      # Step 3: Log in to Docker Hub using GitHub secrets
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Step 4: Build and push the Docker image to Docker Hub
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: >
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ github.sha }},
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:latest
